### ISSUE TITLE
Error Code: 31002 Invalid Parameter.

### ISSUE THREAD

**Issue by JaleelNazir** [rahul08M/python3-ccavenue#1]
Can you help me to solve this issue, Not able to contact ccavenue team.

**Comment by rahul08M** [comment]
Is it possible to you to share the full error traceback?  @JaleelNazir

**Comment by JaleelNazir** [comment]
This issue was resolved. It was a problem on the CCAvenue side. Thanks anyway for the response. @rahul08M 

The scenario is that we are running a cron job to get the status of order_no, and I'm receiving the following error message:

`status=1&enc_response=You are not allowed to perform this operation`

I have sent two emails to the CCAvenue team, but it has been four days without any reply.

```
TOKEN = {
        'order_no': order_no
    }
    encrypted_token = TOKEN

curl --location 'https://api.ccavenue.com/apis/servlet/DoWebTrans' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'enc_request=<encrypted_token>' \
--data-urlencode 'access_code=<ACCESS_CODE>' \
--data-urlencode 'request_type=JSON' \
--data-urlencode 'response_type=JSON' \
--data-urlencode 'command=orderStatusTracker'
```

Can you help me out with this issue?

**Comment by rahul08M** [comment]
@JaleelNazir Have tried webhooks. ccavenue provides the option to integrate the webhooks. 

> CCavenue webhook is a feature that allows CCavenue payment gateway to send real-time notifications to merchants or business owners about certain events that take place during a payment transaction. This enables the merchant to take appropriate actions or update their systems in real-time.

https://www.ccavenue.com/article/Receive-real-time-updates-of-key-events-in-your-Merchant-Account-through-CCAvenues-Dynamic-Event-Notifications.jsp

**Comment by JaleelNazir** [comment]
```
import json
import requests
from Crypto.Cipher import AES
from Crypto.Hash import MD5
from Crypto.Util.Padding import pad, unpad
from binascii import hexlify, unhexlify
from django.conf import settings


def encrypt(plain_text, key):
    key = MD5.new(key.encode('utf-8')).digest()
    init_vector = b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f'
    cipher = AES.new(key, AES.MODE_CBC, init_vector)
    encrypted_text = cipher.encrypt(pad(plain_text.encode('utf-8'), 16))
    return hexlify(encrypted_text).decode('utf-8')

def decrypt(encrypted_text, key):
    key = MD5.new(key.encode('utf-8')).digest()
    init_vector = b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f'
    cipher = AES.new(key, AES.MODE_CBC, init_vector)
    decrypted_text = unpad(cipher.decrypt(unhexlify(encrypted_text)), 16)
    return decrypted_text.decode('utf-8')

def get_payment_status_fororder():
    working_key = settings.PAYMENT_SECRET_CCAV_WORKING_KEY
    access_code = settings.PAYMENT_SECRET_CCAV_ACCESS_CODE
    merchant_json_data = {
        'order_no': 'qwertyu',
        'reference_no': 'qwertyu'
    }
    merchant_data = json.dumps(merchant_json_data)
    encrypted_data = encrypt(merchant_data, working_key)
    final_data = {
        'enc_request': encrypted_data,
        'access_code': access_code,
        'command': 'orderStatusTracker',
        'request_type': 'JSON',
        'response_type': 'JSON',
        'reference_no':'qwertyu',
        'order_no':"qwertyu"
    }
    response = requests.post("https://apitest.ccavenue.com/apis/servlet/DoWebTrans", data=final_data, verify=False)
    information = response.text.split('&')
    status = ''
    for item in information:
        info_value = item.split('=')
        if info_value[0] == 'enc_response':
            status = decrypt(info_value[1].strip(), working_key)
    obj = json.loads(status)

```

I have attempted this from a whitelisted outgoing IP, but it is not working. Here is the complete code. Could you please point out any issues or errors that might be causing the problem? @rahul08M

**Comment by JaleelNazir** [comment]
we don't want to implement webhooks.

**Comment by JaleelNazir** [comment]
For the `orderStatusTracker` API, we had to share our outgoing server IPs to be whitelisted on the CCAV side. Once that was done, it started working.

@rahul08M What are the advantages of using webhooks compared to calling status APIs from cron? Could you please share your experience?

**Comment by rahul08M** [comment]
@JaleelNazir Based on my experience, below are webhook advantages

**Real-time updates**: With webhooks, you can receive instant updates about payment status changes, which means you can take immediate action if needed.

**Automation**: Webhooks allow you to automate your payment processing workflow, reducing the need for manual intervention.

**Improved reliability**: Webhooks provide a more reliable way to receive payment notifications than relying on polling or manually checking for updates.
